# Generated by Django 4.2.11 on 2024-05-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sex",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
