# Generated by Django 4.2.11 on 2024-05-27 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_sex"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("major", models.CharField(max_length=20)),
                ("double_major", models.CharField(blank=True, max_length=20)),
                ("grades", models.CharField(max_length=20)),
                ("skills", models.CharField(max_length=100)),
                ("award_part", models.CharField(max_length=20)),
                ("award_detail", models.TextField(blank=True)),
                ("club_part", models.CharField(max_length=20)),
                ("club_detail", models.TextField(blank=True)),
                ("project_part", models.CharField(max_length=20)),
                ("project_detail", models.TextField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
