# Generated by Django 4.2.11 on 2024-05-31 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Senior_Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job", models.CharField(max_length=20)),
                ("major", models.CharField(max_length=20)),
                ("double_major", models.CharField(max_length=20)),
                ("sex", models.CharField(max_length=4)),
                ("grades", models.CharField(max_length=20)),
                ("skills", models.CharField(max_length=100)),
                ("award_part", models.CharField(max_length=100)),
                ("club_part", models.CharField(max_length=100)),
                ("project_part", models.CharField(max_length=100)),
            ],
        ),
    ]
