# Generated by Django 4.2.11 on 2024-06-01 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("matching", "0002_alter_senior_profile_double_major"),
    ]

    operations = [
        migrations.CreateModel(
            name="Embedded_Senior_Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("major_embedding", models.JSONField(blank=True)),
                ("double_major_embedding", models.JSONField(blank=True)),
                ("grades_embedding", models.JSONField(blank=True)),
                ("skills_embedding", models.JSONField(blank=True)),
                ("award_part_embedding", models.JSONField(blank=True)),
                ("club_part_embedding", models.JSONField(blank=True)),
                ("project_part_embedding", models.JSONField(blank=True)),
                (
                    "senior_info",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="matching.senior_profile",
                    ),
                ),
            ],
        ),
    ]
