# Generated by Django 4.2.11 on 2024-06-01 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matching", "0003_embedded_senior_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="embedded_senior_profile",
            name="double_major_embedding",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
