# Generated by Django 4.2.11 on 2024-06-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matching", "0004_alter_embedded_senior_profile_double_major_embedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="senior_profile",
            name="name",
            field=models.CharField(default="name", max_length=20),
            preserve_default=False,
        ),
    ]
